## To implement
repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn",
            "--fail-under=5.0",
          ]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args:
          [
            "./src/",
          ]