name: CI

on: [push]

jobs:
  checks:
    name: Initial checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Testing
      run: |
        pytest test/test.py
    - name: Analysing the code with pylint
      run: |
        pylint ./src/ --fail-under=4.0
    - name: Analysing the code with black
      run: |
        black ./src/ --check --verbose
  docker:
    needs: [checks]
    if: github.ref == 'refs/heads/main'
    name: Docker image and deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          dbougie/log680eq12
        tags: |
          latest
          type=sha
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: dbougie
        password: G3JoWgCH*Z1e
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    